document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<!--[if lte IE 9]>     <html class=\'no-js lte-ie9\'> <![endif]-->");
document.writeln("<!--[if gt IE 9]><!--> <html class=\'no-js\'> <!--<![endif]-->");
document.writeln("    <head></head>");
document.writeln("");
document.writeln("    <body class=\'blog-landing\'>");
document.writeln("");
document.writeln("");
document.writeln("        <div  data-dm-tmpl=\'dm-app\'");
document.writeln("            data-dm-app");
document.writeln("            data-app-model=\'{\'apiBasePath\':\'api\', \'basePath\':\'\',\'homePath\':\'\',\'routeBlacklist\':[]}\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<header class=\'header \' role=\'banner\' data-dm-tmpl=\'header\' data-header>");
document.writeln("  <div class=\'cf container\'>");
document.writeln("    <div class=\'burger-btn--wrap\' data-burger-wrap>");
document.writeln("      <button class=\'burger-btn\' data-burger>");
document.writeln("        <span></span>");
document.writeln("        <span></span>");
document.writeln("        <span></span>");
document.writeln("      </button>");
document.writeln("      <div class=\'heading--loader\'>");
document.writeln("        <div class=\'heading--loader-inner\' data-ib-target></div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <!--导航栏菜单 ！！！！在这里！！！！！！！-->");
document.writeln("    <!--<nav class=\'site-nav site-nav&#45;&#45;is-home\' data-site-nav role=\'navigation\'>-->");
document.writeln("    <nav class=\'site-nav g-md-col-6 g-lg-col-11 g-md-push-1 g-lg-col-11 g-lg-col-11 site-nav--is-home\' data-site-nav role=\'navigation\'>");
document.writeln("      <ul class=\'cf unstyled site-nav--list\'>");
document.writeln("        <li class=\'site-nav--list-item site-nav--home site-nav--deepmind\'>");
document.writeln("          <a class=\'no-underline white p--module\' href=\'/\' data-has-subitems>主页</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("");
document.writeln("          <li class=\'site-nav--list-item site-nav--research\' data-primary-nav-item>");
document.writeln("            <a class=\'no-underline white p--module\' href=\'/research/\' data-has-subitems>");
document.writeln("              资源");
document.writeln("            </a>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </li>");
document.writeln("");
document.writeln("          <li class=\'site-nav--list-item site-nav--applied\' data-primary-nav-item>");
document.writeln("            <a class=\'no-underline white p--module\' href=\'/applied/\' data-has-subitems>");
document.writeln("              博客");
document.writeln("            </a>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </li>");
document.writeln("");
document.writeln("          <li class=\'site-nav--list-item site-nav--research\' data-primary-nav-item>");
document.writeln("            <a class=\'no-underline white p--module\' href=\'/blog/\' data-has-subitems>");
document.writeln("               段子手");
document.writeln("            </a>");
document.writeln("");
document.writeln("");
document.writeln("          </li>");
document.writeln("");
document.writeln("          <li class=\'site-nav--list-item site-nav--generic\' data-primary-nav-item>");
document.writeln("            <a class=\'no-underline white p--module\' href=\'/myself/\' data-has-subitems>");
document.writeln("              我是谁");
document.writeln("            </a>");
document.writeln("");
document.writeln("");
document.writeln("          <!-- </li> -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("      </ul>");
document.writeln("");
document.writeln("    </nav>");
document.writeln("");
document.writeln("  </div>");
document.writeln("");
document.writeln("");
document.writeln("<!--折叠按钮，！！！！！在这里-->");
document.writeln("");
document.writeln("");
document.writeln("  <div class=\'menu bg-grey-light\' data-dm-tmpl=\'menu\'>");
document.writeln("    <div class=\'menu--logo-wrapper\'>");
document.writeln("      <img src=\'/static/v0.0.0/images/deepmind_logo_swirl.png\' class=\'menu--logo\'>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'cf container relative\'>");
document.writeln("");
document.writeln("");
document.writeln("      <!--<section class=\'g-sm-col-4 g-md-col-3 g-lg-col-3  menu-item menu-item&#45;&#45;research\'>-->");
document.writeln("      <section class=\'g-sm-col-4 g-md-col-2 g-lg-col-3 g-lg-push-1 menu-item menu-item--research\'>");
document.writeln("        <header class=\'menu-item--header\'>");
document.writeln("          <!--<h1 class=\'h5 menu-item&#45;&#45;heading border-bottom\'>-->");
document.writeln("          <h1 class=\'h4 menu-item--heading border-bottom\'>");
document.writeln("            <a class=\'no-underline\' href=\'/\'>主页</a>");
document.writeln("          </h1>");
document.writeln("        </header>");
document.writeln("");
document.writeln("        <div class=\'menu-item--items\'>");
document.writeln("");
document.writeln("          <h2 class=\'h6 menu-item--item-heading border-bottom no-link\'>");
document.writeln("");
document.writeln("              主要");
document.writeln("");
document.writeln("          </h2>");
document.writeln("");
document.writeln("");
document.writeln("          <ul class=\'cf unstyled\'>");
document.writeln("");
document.writeln("            <li class=\'left menu-item--items--subitem\'>");
document.writeln("              <a class=\'no-underline black p--module\' href=\'/research/alphago/\'>");
document.writeln("                <strong>face</strong>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\'left menu-item--items--subitem\'>");
document.writeln("              <a class=\'no-underline black p--module\' href=\'/research/dqn/\'>");
document.writeln("                <strong>human pose estimation</strong>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\'left menu-item--items--subitem\'>");
document.writeln("              <a class=\'no-underline black p--module\' href=\'/research/dnc/\'>");
document.writeln("                <strong>Capsules</strong>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("          </ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          <h2 class=\'h6 menu-item--item-heading border-bottom None\'>");
document.writeln("");
document.writeln("            <a class=\'no-underline\' href=\'/research/open-source/\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            </a>");
document.writeln("");
document.writeln("          </h2>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'menu-item--latest-news\'>");
document.writeln("  <!--<h4 class=\'h4 menu-item&#45;&#45;latest-news-heading\'>-->");
document.writeln("  <h4 class=\'menu-item--latest-news-heading\'>");
document.writeln("    近日更新");
document.writeln("  </h4>");
document.writeln("  <a class=\'h6 underline\' href=\'/blog/label/\'>标签的局限</a>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("      </section>");
document.writeln("      <!---->");
document.writeln("");
document.writeln("      <!--<section class=\'g-sm-col-4 g-md-col-3 g-lg-col-3 g-md-gut g-lg-gut menu-item menu-item&#45;&#45;applied\'>-->");
document.writeln("      <section class=\'g-sm-col-4 g-md-col-2 g-lg-col-3 g-md-gut g-lg-gut menu-item menu-item--applied\'>");
document.writeln("        <header class=\'menu-item--header\'>");
document.writeln("          <!--<h1 class=\'h5 menu-item&#45;&#45;heading border-bottom\'>-->");
document.writeln("          <h1 class=\'h4 menu-item--heading border-bottom\'>");
document.writeln("            <a class=\'no-underline\' href=\'/applied/\'>博客</a>");
document.writeln("          </h1>");
document.writeln("        </header>");
document.writeln("");
document.writeln("        <div class=\'menu-item--items\'>");
document.writeln("");
document.writeln("          <h2 class=\'h6 menu-item--item-heading border-bottom None\'>");
document.writeln("");
document.writeln("            <a class=\'no-underline\' href=\'/applied/deepmind-health/\'>");
document.writeln("");
document.writeln("              1");
document.writeln("");
document.writeln("            </a>");
document.writeln("");
document.writeln("          </h2>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'menu-item--latest-news\'>");
document.writeln("  <!--<h4 class=\'h4 menu-item&#45;&#45;latest-news-heading\'>-->");
document.writeln("  <h4 class=\'menu-item--latest-news-heading\'>");
document.writeln("    这是什么鬼？");
document.writeln("  </h4>");
document.writeln("  <a class=\'h6 underline\' href=\'/blog/deepmind-meet-android/\'>111</a>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("      </section>");
document.writeln("      <!---->");
document.writeln("      <!--<div class=\'cf lg-hide\'></div>-->");
document.writeln("      <!---->");
document.writeln("");
document.writeln("      <!--<section class=\'g-sm-col-4 g-md-col-3 g-lg-col-3 g-lg-gut menu-item menu-item&#45;&#45;deepmind\'>-->");
document.writeln("      <section class=\'g-sm-col-4 g-md-col-2 g-lg-col-3 g-md-gut g-lg-gut menu-item menu-item--deepmind\'>");
document.writeln("        <header class=\'menu-item--header\'>");
document.writeln("          <!--<h1 class=\'h5 menu-item&#45;&#45;heading border-bottom\'>-->");
document.writeln("          <h1 class=\'h4 menu-item--heading border-bottom\'>");
document.writeln("            <a class=\'no-underline\' href=\'/child/\'>儿童节致敬</a>");
document.writeln("          </h1>");
document.writeln("        </header>");
document.writeln("        <div class=\'menu-item--items\'>");
document.writeln("");
document.writeln("          <h2 class=\'h6 menu-item--item-heading border-bottom None\'>");
document.writeln("");
document.writeln("            <a class=\'no-underline\' href=\'/child/min/\'>");
document.writeln("");
document.writeln("              敏妹想吃猪蹄");
document.writeln("");
document.writeln("            </a>");
document.writeln("");
document.writeln("          </h2>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          <h2 class=\'h6 menu-item--item-heading border-bottom None\'>");
document.writeln("");
document.writeln("            <a class=\'no-underline\' href=\'/child/bo\'>");
document.writeln("");
document.writeln("             张博同学一定要发奋图强");
document.writeln("");
document.writeln("            </a>");
document.writeln("");
document.writeln("          </h2>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("      </section>");
document.writeln("      <!---->");
document.writeln("");
document.writeln("      <div class=\'cf\'></div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--<div class=\'g-sm-col-4 g-md-col-4 g-lg-col-9 border-top menu-item&#45;&#45;generic\'>-->");
document.writeln("<div class=\'g-sm-col-4 g-md-col-4 g-lg-col-8 border-top menu-item--generic\'>");
document.writeln("  <ul class=\'menu-item--generic-list unstyled\'>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item \'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/\'>");
document.writeln("          <strong>现在</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item \'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/blog/\'>");
document.writeln("          <strong>还在 &amp; 搭建</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item \'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/myself/\'>");
document.writeln("          <strong>我是谁?</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item \'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/press/\'>");
document.writeln("          <strong>我在哪？</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item last-item\'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/terms-and-conditions/\'>");
document.writeln("          <strong>我在干什么？</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("    <li class=\'menu-item--generic--item last-item\'>");
document.writeln("        <a class=\'black no-underline p--module\' href=\'/privacy-policy/\'>");
document.writeln("          <strong>以后都会有料的</strong>");
document.writeln("        </a>");
document.writeln("      </li>");
document.writeln("");
document.writeln("  </ul>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <span");
document.writeln("    class=\'page-load-progress\'");
document.writeln("    data-dm-tmpl=\'page-load-progress\'>");
document.writeln("  </span>");
document.writeln("</header>");
document.writeln("");
document.writeln("          <main class=\'wrapper \' role=\'main\' data-dm-tmpl=\'wrapper\' data-wrapper>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'page page-blog-listing\' data-dm-page=\'blog-listing\'>");
document.writeln("  <section class=\'section--block\'>");
document.writeln("    <div class=\'container cf\'>");
document.writeln("      <header class=\'section--header g-sm-col-4 g-lg-col-11 g-lg-push-1\'>");
document.writeln("  <h1 class=\'h6 uppercase left \'>一个正经人的 &amp; 学术遐想 </h1>");
document.writeln("");
document.writeln("    <a class=\'btn right\' href=\'/blog/feed/basic/\' data-ignore-link-click>");
document.writeln("");
document.writeln("			<svg class=\'icon icon-rss icon-white\'>");
document.writeln("				<title>点我没用</title>");
document.writeln("				<use xmlns:xlink=\'http://www.w3.org/1999/xlink\' xlink:href=\'#rss\'></use>");
document.writeln("			</svg>");
document.writeln("");
document.writeln("    	点我 没用");
document.writeln("	</a>");
document.writeln("");
document.writeln("</header>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--  <p><h1 class=\'heading heading--research h1\'>");
document.writeln("  <a class=\'underline\' href=\'/blog/label/\'>热烈欢迎 敏妹小朋友 来网站里面踩一踩，撒花#\/\/0.0/#</a>");
document.writeln("</h1></p>  -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <link rel=\'stylesheet\' media=\'all\' href=\'/html_style/2.css\' data-turbolinks-track=\'true\' />");
document.writeln("<script src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-006f0807613f7765e38bf9babe1dea07.js\' data-turbolinks-track=\'true\'></script>");
document.writeln("");
document.writeln("<section>");
document.writeln("        <div class=\'hero-logo-circles\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-red-semi-085b4e44d49b2ffe935cc1b2b3094ce8.svg\' alt=\'Index portal red semi\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-red-be5d1b8a52c13bf286560aba3e4c8c30.svg\' alt=\'Index portal red\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-orange-semi-d2010f0f8e41e03dbf2b5c52166abe4b.svg\' alt=\'Index portal orange semi\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-orange-b3bddfb758b91d22f43d0e14ed8e29da.svg\' alt=\'Index portal orange\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-yellow-semi-545681fe77ff01659d472bd379a9f38b.svg\' alt=\'Index portal yellow semi\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-yellow-ff207a58ad4f450ea9ac0e17224b39f1.svg\' alt=\'Index portal yellow\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-green-semi-2d5bc571ee90e710d93f7ae7ddd06e85.svg\' alt=\'Index portal green semi\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-green-6ab85a1e7343a232273868031b242806.svg\' alt=\'Index portal green\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-blue-semi-7333f1323549be50644411b691b173dd.svg\' alt=\'Index portal blue semi\'>");
document.writeln("          <img class=\'hero-logo-circle\' src=\'https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-portal-blue-92fc2c151190795bd0147c03d4fb8352.svg\' alt=\'Index portal blue\'>");
document.writeln("");
document.writeln("      </div></section>");
document.writeln("");
document.writeln("<!--  文章列表在这里-->");
document.writeln("<h5>&nbsp;</h5>");
document.writeln("");
document.writeln("");
document.writeln("<p>&nbsp;</p>");
document.writeln("    </body>");
document.writeln("</html>");
document.writeln("");