document.writeln("<!DOCTYPE html>");
document.writeln("<!--[if lte IE 9]>     <html class=\'no-js lte-ie9\'> <![endif]-->");
document.writeln("<!--[if gt IE 9]><!--> <html class=\'no-js\'> <!--<![endif]-->");
document.writeln("    <head></head>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网页尾部-->");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("          </main>");
document.writeln("          <div class=\'nav-mask\'></div>");
document.writeln("          <section class=\'search fixed top-0 right-0 bottom-0 left-0\' data-dm-tmpl=\'search\'>");
document.writeln("  <div class=\'cf container relative h100\'>");
document.writeln("    <section class=\'search--input-wrapper relative\'>");
document.writeln("      <div class=\'g-md-col-1 g-lg-col-1 search--mega-icon\'>");
document.writeln("        <svg class=\'icon icon-search icon-search-large\'>");
document.writeln("          <use xlink:href=\'#search_large\'></use>");
document.writeln("        </svg>");
document.writeln("      </div>");
document.writeln("      <input class=\'g-sm-col-4 g-md-col-5 g-lg-col-11 search--mega-input\' type=\'search\' name=\'search\' placeholder=\'Search DeepMind\' data-search-input>");
document.writeln("      <span class=\'p--meta grey-mid uppercase absolute right-0\' data-total-results data-scroll-item></span>");
document.writeln("    </section>");
document.writeln("    <section class=\'search--input-wrapper search--input-wrapper--sticky\'>");
document.writeln("      <div class=\'g-md-col-1 g-lg-col-1 search--mega-icon\'>");
document.writeln("        <svg class=\'icon icon-search icon-search-large\'>");
document.writeln("          <use xlink:href=\'#search_large\'></use>");
document.writeln("        </svg>");
document.writeln("      </div>");
document.writeln("      <input class=\'g-sm-col-4 g-md-col-5 g-lg-col-11 search--mega-input\' type=\'search\' name=\'search\' placeholder=\'Search DeepMind\' data-search-input>");
document.writeln("    </section>");
document.writeln("    <div class=\'search--results-wrapper\' data-results-wrap></div>");
document.writeln("    <div class=\'g-sm-col-4 text-center search--results-btn-wrap\'>");
document.writeln("      <a class=\'btn\' href=\'#\' data-results-page-btn>Show all results</a>");
document.writeln("    </div>");
document.writeln("    <button class=\'top-0 right-0 black\' data-close-btn>");
document.writeln("      <svg class=\'icon icon-close\'>");
document.writeln("        <title>close</title>");
document.writeln("        <use xlink:href=\'#close\'></use>");
document.writeln("      </svg>");
document.writeln("    </button>");
document.writeln("  </div>");
document.writeln("</section>");
document.writeln("");
document.writeln("<footer class=\'footer bg-grey-light\' role=\'contentinfo\'>");
document.writeln("  <section class=\'cf container\'>");
document.writeln("    <header class=\'g-sm-col-4 g-lg-col-10 g-lg-push-1\'>");
document.writeln("      <h1 class=\'left logo\'>");
document.writeln("        <a href=\'/\'>");
document.writeln("");
document.writeln("            <img src=\'/static/v0.0.0/images/deepmind_logo.png\'");
document.writeln("              srcset=\'/static/v0.0.0/images/deepmind_logo.png 1x, /static/v0.0.0/images/deepmind_logo@2x.png 2x\'");
document.writeln("              alt=\'Yang Sen Ius\'>");
document.writeln("");
document.writeln("        </a>");
document.writeln("      </h1>");
document.writeln("");
document.writeln("      <div class=\'right social-items footer--social-items\'>");
document.writeln("        <p class=\'left grey-mid p--meta\'>");
document.writeln("");
document.writeln("        </p>");
document.writeln("        <ul class=\'left unstyled\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("");
document.writeln("    </header>");
document.writeln("    <nav class=\'g-sm-col-4 g-md-col-3 g-lg-col-4 g-lg-push-1\'>");
document.writeln("      <ul class=\'cf unstyled footer--nav-list\'>");
document.writeln("");
document.writeln("        <li class=\'g-sm-col-4 footer--nav-list--item faux-link-block\'>");
document.writeln("          <a class=\'no-underline grey-dark p--module\' href=\'/myself/\'>Who am I</a>");
document.writeln("          <a class=\'faux-link-block--link\' href=\'/myself/\'>Who am I</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("        <li class=\'g-sm-col-4 footer--nav-list--item faux-link-block\'>");
document.writeln("          <a class=\'no-underline grey-dark p--module\' href=\'/applied/\'>Where am I</a>");
document.writeln("          <a class=\'faux-link-block--link\' href=\'/applied/\'>Where am I</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("        <li class=\'g-sm-col-4 footer--nav-list--item faux-link-block\'>");
document.writeln("          <a class=\'no-underline grey-dark p--module\' href=\'/myself/\'>留言</a>");
document.writeln("          <a class=\'faux-link-block--link\' href=\'https://github.com/yangsenius/yangsenius.github.io/issues\'>学术</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("        <li class=\'g-sm-col-4 footer--nav-list--item faux-link-block\'>");
document.writeln("          <a class=\'no-underline grey-dark p--module\' href=\'/careers/\'>段子</a>");
document.writeln("          <a class=\'faux-link-block--link\' href=\'/careers/\'>段子</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("      </ul>");
document.writeln("    </nav>");
document.writeln("    <div class=\'g-sm-col-4 g-md-col-2 g-lg-col-5 right\'>");
document.writeln("      <ul class=\'cf unstyled footer--nav-list\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <li class=\'g-sm-col-4 footer--nav-list--item-secondary\'>");
document.writeln("          <a class=\'no-underline grey-mid p--module\' href=\'/myself/\'>所有文章均为原创，转载请注明来源</a>");
document.writeln("        </li>");
document.writeln("");
document.writeln("      </ul>");
document.writeln("      <p class=\'grey-mid-light p--module\'>© 2018 Blog Design - Wechat-> yangsenius</p>");
document.writeln("    </div>");
document.writeln("  </section>");
document.writeln("</footer>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("<section class=\'cookie-banner is-hidden\'");
document.writeln("	data-dm-tmpl=\'cookie-banner\'");
document.writeln("	data-last-updated=\'1526378400\'>");
document.writeln("	<div class=\'container cf\'>");
document.writeln("		<div class=\'rich-text\'><p>本网站借鉴了多个网站的元素，你也可以定制属于自己的个性化博客。<a href=\'/myself/\'> 联系</a></p></div>");
document.writeln("		<div data-close>");
document.writeln("			<svg class=\'icon icon-close\'>");
document.writeln("				<title>close</title>");
document.writeln("				<use xlink:href=\'#close\'></use>");
document.writeln("			</svg>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</section>");
document.writeln("");
document.writeln("");
document.writeln("        <script type=\'text/javascript\' src=\'/html_style/b.js\' defer></script>");
document.writeln("        <!-- Google Analytics -->");
document.writeln("");
document.writeln("<script>");
document.writeln("(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){");
document.writeln("(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),");
document.writeln("m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)");
document.writeln("})(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');");
document.writeln("");
document.writeln("ga(\'create\', \'UA-83756414-1\', \'auto\');");
document.writeln("ga(\'send\', \'pageview\');");
document.writeln("</script>");
document.writeln("");
document.writeln("<!-- End Google Analytics -->");
document.writeln("");