document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<!--[if lte IE 9]>     <html class=\'no-js lte-ie9\'> <![endif]-->");
document.writeln("<!--[if gt IE 9]><!--> <html class=\'no-js\'> <!--<![endif]-->");
document.writeln("    <head>");
document.writeln("");
document.writeln("      <link rel=\'stylesheet\' href=\'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css\'>");
document.writeln("");
document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\' />");
document.writeln("<meta charset=\'utf-8\' />");
document.writeln("");
document.writeln("<title>Yangenius养成记</title>");
document.writeln("<meta name=\'description\' content=\'\' />");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, minimum-scale=1\' />");
document.writeln("");
document.writeln("<link rel=\'shortcut icon\' href=\'/static/v0.0.0/appIcons/favicon.png\' type=\'image/x-icon\' />");
document.writeln("<link rel=\'apple-touch-icon\' href=\'/static/v0.0.0/appIcons/apple-touch-icon.png\' />");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'80x80\' href=\'/static/v0.0.0/appIcons/apple-touch-icon-80x80.png\' />");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'120x120\' href=\'/static/v0.0.0/appIcons/apple-touch-icon-120x120.png\' />");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'152x152\' href=\'/static/v0.0.0/appIcons/apple-touch-icon-152x152.png\' />");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'167x167\' href=\'/static/v0.0.0/appIcons/apple-touch-icon-167x167.png\' />");
document.writeln("");
document.writeln("<meta property=\'og:title\' content=\'Super养成记 &amp;  | YangSENius\'>");
document.writeln("<meta property=\'og:url\' content=\'https://yangsenius.github.io\'>");
document.writeln("<meta property=\'og:description\' content=\'\'>");
document.writeln("<meta property=\'og:site_name\' content=\'杨森\'>");
document.writeln("");
document.writeln("<meta name=\'twitter:card\' content=\'summary\'>");
document.writeln("<meta name=\'twitter:url\' content=\'https://yangsenius.github.io\'>");
document.writeln("<meta name=\'twitter:title\' content=\'杨森\'>");
document.writeln("<meta name=\'twitter:description\' content=\'\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<link rel=\'alternate\' type=\'application/rss+xml\' title=\'RSS \' href=\'/blog/\' />");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <link rel=\'stylesheet\' type=\'text/css\' href=\'/html_style/a.css\'>");
document.writeln("");
document.writeln("        <!--[if lte IE 9]>");
document.writeln("          <script src=\'/static/v0.0.0/js/vendor/classList-55aabd716f.min.js\'></script>");
document.writeln("          <script src=\'/static/v0.0.0/js/vendor/requestAnimationFrame-d5eb311bf6.js\'></script>");
document.writeln("        <![endif]-->");
document.writeln("");
document.writeln("        <script src=\'/html_style/a.js\'></script>");
document.writeln("");
document.writeln("        <script>(function(){var fn=function(){window.DM_APP_ERROR={timer:null,delay:3e3,hasError:!1,errorFn:function(r){console.error(\'DM_APP_ERROR\',r),window.DM_APP_ERROR.hasError=!0}},window.DM_APP_ERROR.timer=setTimeout(function(){window.DM_APP_ERROR.hasError?[].slice.call(document.querySelectorAll(\'[data-scroll-item]\')).forEach(function(r){return r.className+=\' show\'}):document.documentElement.className+=\' no-js\'},window.DM_APP_ERROR.delay),window.addEventListener(\'error\',window.DM_APP_ERROR.errorFn,!1)};fn();})();</script>");
document.writeln("    </head>");
document.writeln("");
document.writeln("    <body class=\'blog-landing\'>");
document.writeln("    </body>");
document.writeln("</html>");
document.writeln("");